sudo: false

language: ruby

git:
  depth: 1

install: true

notifications:
  disable: true

rvm:
  - 2.1
  - 2.2
  - 2.3.3

install:
  - bundle install

before_script:
  - ./bin/start-toxiproxy.sh

script:
  - bundle exec rake test
